channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.19.2
  - pip>=20.3.3
  - python=3.8
  - scipy>=1.5.2
  - setuptools>=51.3.3
  - jupyterlab
  - ipywidgets
  - ffmpeg
  - pip
  - pip:
      - matplotlib
      - exoplanet
      - starry
      - starry_process
      - lightkurve
      - arviz
      - corner
      - seaborn
      - pandas