channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - emcee
    - exoplanet
    - starry
    - starry_process
    - lightkurve
    - corner
    - arviz ~= 0.14.0
    - jupyterlab
    - matplotlib
    - numpy 
    - scipy
    - seaborn
    - ipywidgets
