channels:
  - conda-forge
  - defaults
dependencies:
  - pip>=20.3.3
  - python=3.8
  - setuptools>=51.3.3
  - ffmpeg
  - hdf5
  - netcdf4
  - numpy~=1.20.3
  - scipy~=1.5.2
  - pip
  - pip:
      - matplotlib
      - exoplanet
      - starry
      - starry_process
      - lightkurve
      - arviz==0.12.0
      - corner
      - seaborn
      - pandas
      - netcdf4~=1.6.4
      - jupyterlab
      - ipywidgets
